### ISSUE TITLE
No wheels for Python 3.9

### ISSUE THREAD

**Issue by dionhaefner** [deepmind/tree#22]
#1++. There are wheels for 3.8 by now, but 3.9 is missing.

**Comment by ClaasRostock** [comment]
Dear Sergei,

I saw that the CI pipeline ran 3 days ago and it seems it successfully built wheels for Python 3.9
[https://github.com/deepmind/tree/runs/2297924278?check_suite_focus=true](url)

Could you make available here the wheel for Windows? E.g.
dm_tree-0.1.6-cp39-cp39-win_amd64.whl

Or make it available via PyPI, alternatively ?

'Would be great and much appreciated!  Thank you!

 Best regards,

Claas

@superbobry

**Comment by superbobry** [comment]
Apologies this took so long. I've pushed 3.9 wheels to PyPI today.
