### ISSUE TITLE
Is deep copy default?

### ISSUE THREAD

**Issue by bibbygoodwin** [deepmind/tree#25]
Quite a simple question - I mostly use `tree` for shuffling and slicing dictionaries of same-sized (numpy) arrays, with `tree.map_structure`. From what I've seen when using this, the dictionary returned by calls to `map_structure` will be `copy.deepcopy`'s of the original data (which is what I want to avoid unexpected side effects).

Could you confirm this, though? And is this default behaviour through `tree`'s operation?

Thank you!

**Comment by superbobry** [comment]
IIRC `tree` does not copy the leaf nodes (i.e. things it cannot map through), so it shouldn't copy arrays. 

```
>>> import tree
>>> import numpy as np
>>> d = {"x": np.array([42])}
>>> id(d["x"])
140160994250960
>>> id(tree.map_structure(lambda v: v, d)["x"])
140160994250960
```
