### ISSUE TITLE
Cannot install dm-tree on raspberry pi 3 (armv7l)

### ISSUE THREAD

**Issue by neeraj-partha** [deepmind/tree#34]
'pip install dm-tree' hangs forever on Raspberry pi 3 (armv7l) with Raspbian buster OS. can you please help.
Thanks

**Comment by superbobry** [comment]
Hi @neeraj-partha! We don't currently ship armv7l wheels, and I'm afraid we don't have immediate plans to do so. I have no means of reproducing this locally, but it is possible that Rapberry Pi has a hard time compiling tree from source.
