### ISSUE TITLE
ModuleNotFoundError: No module named 'tree'

### ISSUE THREAD

**Issue by Klord123** [deepmind/tree#4]
Installed with `pip3 install dm-tree`

Mac OSX: 10.14.6
Python: 3.7.6
Pip: 20.0.2

`pip3 show dm-tree` outputs:
`
    Name: dm-tree  
    Version: 0.1.4  
    Summary: Tree is a library for working with nested data structures.  
    Home-page: https://github.com/deepmind/tree  
    Author: DeepMind  
    Author-email: tree-copybara@google.com  
    License: Apache 2.0  
    Location: /usr/local/lib/python3.7/site-packages  
    Requires: six  
    Required-by: 
`

This appears to be an issue only on a Mac system. It does not appear on my Ubuntu 18.04 or Windows 10 machine.

**Comment by Millebean** [comment]
Have you found the solution? I am having the same problem on my mac system

**Comment by T-oat** [comment]
same problem. /cry

**Comment by T-oat** [comment]
bingo! should download zip and un-zip package,Maybe there is something wrong with the pip tool

**Comment by shhh9** [comment]
You might have installed both 'tree' and 'dm-tree' and pip would get confused. Try uninstall tree and reinstall dm-tree. It fixed this problem for me.
