### ISSUE TITLE
Cannot install dm-tree 0.1.6 on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by fxpoignart** [deepmind/tree#46]
pip install fails with error:

ERROR: dm_tree-0.1.6-cp38-cp38-manylinux_2_24_x86_64.whl is not a supported wheel on this platform.

**Comment by Byung-June** [comment]
My platform is 'Ubuntu 18.04.5 LTS', and I also got this problem!
Failed building wheel for dm-tree

**Comment by mobraine** [comment]
> 
> 
> My platform is 'Ubuntu 18.04.5 LTS', and I also got this problem!
> Failed building wheel for dm-tree

Same here!

**Comment by pvasek** [comment]
I got the same error on `Ubuntu 18.04.1` with `pip` `20.1.1` version. 

Once I updated `pip` to `21.1.2` with `pip install --upgrade pip`. The issue disappeared and I was able to install it.

**Comment by amitpandey2194** [comment]
> I got the same error on `Ubuntu 18.04.1` with `pip` `20.1.1` version.
> 
> Once I updated `pip` to `21.1.2` with `pip install --upgrade pip`. The issue disappeared and I was able to install it.

Yes this worked for me too.

**Comment by superbobry** [comment]
Thanks for sharing the fix @pvasek!
