### ISSUE TITLE
Cannot install dm-tree 0.1.6 on Mac OS 10.13.6

### ISSUE THREAD

**Issue by sunji0127** [deepmind/tree#47]
The Exception logs:

pip install dm-tree
Collecting dm-tree
  Using cached dm-tree-0.1.6.tar.gz (33 kB)
Requirement already satisfied: six>=1.12.0 in /Users/sun/anaconda3/lib/python3.8/site-packages (from dm-tree) (1.16.0)
Building wheels for collected packages: dm-tree
  Building wheel for dm-tree (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sun/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"'; __file__='"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-wheel-3w457fjp
       cwd: /private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/tree_test.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  copying tree/tree_benchmark.py -> build/lib.macosx-10.9-x86_64-3.8/tree
  running build_ext
  bazel build //tree:_tree --symlink_prefix=build/temp.macosx-10.9-x86_64-3.8/bazel- --compilation_mode=opt
  Starting local Bazel server and connecting to it...
  Loading:
  Loading: 0 packages loaded
  Analyzing: target //tree:_tree (1 packages loaded, 0 targets configured)
  Analyzing: target //tree:_tree (15 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  Analyzing: target //tree:_tree (18 packages loaded, 33 targets configured)
  INFO: Analyzed target //tree:_tree (25 packages loaded, 339 targets configured).
  INFO: Found 1 target...
  [0 / 17] [Prepa] Writing file tree/_tree.so-2.params
  ERROR: /private/var/tmp/_bazel_sun/52c75caa768e4e6091ff56774050ab09/external/com_google_absl/absl/base/BUILD.bazel:58:11: Linking external/com_google_absl/absl/base/libdynamic_annotations.pic.a failed: (Exit 1): libtool failed: error executing command /usr/bin/libtool @bazel-out/darwin-opt/bin/external/com_google_absl/absl/base/libdynamic_annotations.pic.a-2.params

  Use --sandbox_debug to see verbose messages from the sandbox
  error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
  Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
  Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
  Target //tree:_tree failed to build
  Use --verbose_failures to see the command lines of failed build steps.
  INFO: Elapsed time: 113.779s, Critical Path: 1.37s
  INFO: 34 processes: 31 internal, 3 darwin-sandbox.
  FAILED: Build did NOT complete successfully
  FAILED: Build did NOT complete successfully
  error: command 'bazel' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dm-tree
  Running setup.py clean for dm-tree
Failed to build dm-tree
Installing collected packages: dm-tree
    Running setup.py install for dm-tree ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sun/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"'; __file__='"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-record-sro_c2ze/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sun/anaconda3/include/python3.8/dm-tree
         cwd: /private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/tree_test.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    copying tree/tree_benchmark.py -> build/lib.macosx-10.9-x86_64-3.8/tree
    running build_ext
    bazel build //tree:_tree --symlink_prefix=build/temp.macosx-10.9-x86_64-3.8/bazel- --compilation_mode=opt
    Loading:
    Loading: 0 packages loaded
    Analyzing: target //tree:_tree (0 packages loaded, 0 targets configured)
    INFO: Analyzed target //tree:_tree (3 packages loaded, 6 targets configured).
    INFO: Found 1 target...
    [0 / 2] [Prepa] BazelWorkspaceStatusAction stable-status.txt
    ERROR: /private/var/tmp/_bazel_sun/52c75caa768e4e6091ff56774050ab09/external/com_google_absl/absl/base/BUILD.bazel:58:11: Linking external/com_google_absl/absl/base/libdynamic_annotations.pic.a failed: (Exit 1): libtool failed: error executing command /usr/bin/libtool @bazel-out/darwin-opt/bin/external/com_google_absl/absl/base/libdynamic_annotations.pic.a-2.params

    Use --sandbox_debug to see verbose messages from the sandbox
    error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
    Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
    Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
    Target //tree:_tree failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 0.756s, Critical Path: 0.13s
    INFO: 5 processes: 5 internal.
    FAILED: Build did NOT complete successfully
    FAILED: Build did NOT complete successfully
    error: command 'bazel' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sun/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"'; __file__='"'"'/private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-install-xcyi74j_/dm-tree_408097f15f644bdf892b959d076148ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9l/m0257wfn1h1557n075s865l80000gp/T/pip-record-sro_c2ze/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sun/anaconda3/include/python3.8/dm-tree Check the logs for full command output.
(base) localhost:df9c56805bf5ebf331fb1ad733d0d4fd32ee3405fd8d88ed09 sun$

**Comment by Asriel31** [comment]
Did you found a counter measure to this issue, I'm in the same way.
It seems related to the mac osx 10.13 and the lib.macosx-10.9-x86_64-3.8 there is a part of your problem became from the python version.
But even from me this part of the problem seems solved it remains I cannot install dm-tree.
see https://pypi.org/project/dm-tree/#files the expected package doesn't exist

**Comment by superbobry** [comment]
Please give the latest wheels on PyPI a try and reopen the issue if it still affect you.
