### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [deepmind/tree#48]
Problem
---------
On aarch64, ‘pip install dm-tree’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install dm-tree’ should download the wheels from pypi

Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by LastShell73** [comment]
To date, is there a wheel available on aarch64?

**Comment by ngam** [comment]
as an aside: available on conda-forge fyi
