### ISSUE TITLE
Please add a build file for Apple M1

### ISSUE THREAD

**Issue by saleh-mir** [deepmind/tree#69]
Hi there 

Apparently, a lot of packages including the `tf-agents` library are dependant on this library. It would be great if you could add a build for Apple's M1 macs.

Thank you so much for your time and affords

**Comment by andyk** [comment]
I'd deeply appreciate if you did this too!

**Comment by DemianVoorhagen6** [comment]
Would love this as well

**Comment by SauravMaheshkar** [comment]
I was able to install dm-tree on a M1 by installing directly from github using pip. (But make sure you have `cmake` installed)
```
pip install cmake
pip install git+git://github.com/deepmind/tree.git
```

Hope this helps 😁
