### ISSUE TITLE
`PyUnicode_AsUTF8` was not declared in this scope; did you mean `PyUnicode_Type`?

### ISSUE THREAD

**Issue by joshiayush** [deepmind/tree#74]
When building tree locally I get the following error saying `PyUnicode_AsUTF8` was not declared in this scope; did you mean `PyUnicode_Type`?.

<a href="#environment">Environment information</a>

 ```shell
/Python/tree/tree/tree.cc: In function ‘std::string tree::{anonymous}::PyObjectToString(PyObject*)’:
/Python/tree/tree/tree.cc:86:19: error: ‘PyUnicode_AsUTF8’ was not declared in this scope; did you mean ‘PyUnicode_Type’?
   86 |     std::string s(PyUnicode_AsUTF8(str));
      |                   ^~~~~~~~~~~~~~~~
      |                   PyUnicode_Type
make[2]: *** [CMakeFiles/_tree.dir/build.make:76: CMakeFiles/_tree.dir/tree.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/_tree.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

<div id="environment"></div>

__Environment information__
* OS: `Ubuntu 20.04.3 LTS`
* Python: `Python 3.8.10`
* CMake: `cmake version 3.22.1`
* absl version: `b452e5c2743e7489b4ba7f16ecd51c516d7cd8e3`

**Comment by superbobry** [comment]
`PyUnicode_AsUTF8` is part of the official Python [C API](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8), so this should compile AFAICT. 

I will close the issue for now, but feel free to reopen if this is still an issue.

**Comment by joshiayush** [comment]
> `PyUnicode_AsUTF8` is part of the official Python [C API](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsUTF8), so this should compile AFAICT.
> 
> I will close the issue for now, but feel free to reopen if this is still an issue.

Your reply was useless for me. Don't you have some common sense that I would have already solved the problem by myself because its about an year now since I made that post. I don't know how you people come at the top of the contributor list when you can't even solve someone's problem who's in need. Look at the post Dude, I made it on Jan, it's about an year now. I don't need you. People like you can only close the post but couldn't solve it... Because it's far more easy putting a __closed__ label on a issue.

**Comment by joshiayush** [comment]
@superbobry Keep putting a __closed__ label on someone's problem that hasn't been solved yet... You are doing a good job :+1:
