### ISSUE TITLE
 python setup.py install   error

### ISSUE THREAD

**Issue by LiuJiedong-Coder** [deepmind/tree#89]
(tf1_py2) [ljd_XUT@k8s-master01 dm-tree-0.1.7]$ python setup.py install

File "setup.py", line 81
    f'CMake must be installed to build the following extensions: {ext_names}'
                                                                            ^
SyntaxError: invalid syntax

**Comment by dgeor** [comment]
I am getting the same thing, running in a devcontainer - base image: --platform=linux/arm64 python:3.9-slim-bullseye
I am on a m1 mac.

**Comment by dgeor** [comment]
I solved it by running `pip install cmake` - which is needed for the build process.

I also have gcc and build essentials - I do not know if this is relevant however.

Also, if you are using poetry do not add cmake to the deps. You need to pip install it - you want `cmake --version` to work, not `poetry run cmake --version`

**Comment by wookayin** [comment]
That error sounds like the python you ran is `< 3.6` (not supporting f-syntax). I guess it has nothing to do with cmake. Please verify `python --version`, etc.
